#ifndef TA_COMMAND_H_INCLUDE
#define TA_COMMAND_H_INCLUDE

#define TA_CMD_INITDB 0
#define TA_CMD_STORE 1
#define TA_CMD_CHECK 2

#define TA_CHECK_RESULT_CONSISTENT 0
#define TA_CHECK_RESULT_MODIFIED 1
#define TA_CHECK_RESULT_NO_MATCH_FILE 2




#endif 