#ifndef _TA_COMMAND_H
#define _TA_COMMAND_H

#define TA_CMD_INITDB 0
#define TA_CMD_STORE 1
#define TA_CMD_CHECK 2

#define TA_CHECK_RESULT_CONSISTENT 0
#define TA_CHECK_RESULT_MODIFIED 1
#define TA_CHECK_RESULT_NO_MATCH_FILE 2

#define CHECK_PERM_INCONSIS (1<<0)
#define CHECK_UID_INCONSIS (1<<1)
#define CHECK_GID_INCONSIS (1<<2)
#define CHECK_ATIME_INCONSIS (1<<3)
#define CHECK_CTIME_INCONSIS (1<<4)
#define CHECK_MTIME_INCONSIS (1<<5)
#define CHECK_INODE_INCONSIS (1<<6)
#define CHECK_NLINK_INCONSIS (1<<7)
#define CHECK_SIZE_INCONSIS (1<<8)
#define CHECK_BCOUNT_INCONSIS (1<<9)
#define CHECK_SHA256_INCONSIS (1<<10)
#define CHECK_WHIRLPOOL_INCONSIS (1<<11)

#endif 