#ifndef _ERRORCODES_H_INCLUDED
#define  _ERRORCODES_H_INCLUDED

#define ERROR_WRITING_ERROR 14
#define INVALID_ARGUMENT_ERROR 15
#define UNIMPLEMENTED_FUNCTION_ERROR 16
#define INVALID_CONFIGURELINE_ERROR 17
#define IO_ERROR 18
#define VERSION_MISMATCH_ERROR 19
#define EXEC_ERROR 20
#define LOCK_ERROR 21
#define HASH_ALGO_ERROR 30

#endif
